// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
export const parser = LRParser.deserialize({
  version: 14,
  states: "&`OYQPOOOOQO'#Cu'#CuOYQPO'#CwOYQPO'#CxO!oQPO'#CyO!vQPO'#CvOOQO'#Cv'#CvO#eQPO'#CtOfQPO'#CtQOQPOOO#|QPO,59cO$RQPO,59dO$WQPO'#CzOfQPO'#CzOOQO,59e,59eO$fQPO,59eO$nQPO'#ClOOQO,59T,59TOYQPO,59`O$uQPO,59`OOQO1G.}1G.}OOQO1G/O1G/OO!QQPO,59fO%^QPO,59fO!QQPO'#CpO%lQPO1G/POOQO1G/P1G/POOQO,59W,59WO%tQPO,59WOOQO1G.z1G.zOYQPO1G.zOOQO1G/Q1G/QO!QQPO1G/QOOQO,59[,59[OOQO-E6n-E6nOOQO7+$k7+$kO%|QPO1G.rOOQO1G.r1G.rOOQO7+$f7+$fOOQO7+$l7+$lOOQO7+$^7+$^",
  stateData: "&X~OgOSPOS~ORPOSPOTPOUPOVQOXROZSO^TO_TOaUObUOcUO~OU]OVQOXROZSO^TO_TOaUObUOcUO~O[^O~P!QOV`ORjXSjXTjXUjXejXWjXYjX[jX~ORPOSPOTPOUPOehXWhXYhX~OWdO~OYeO~OUfOSnX[nXWnX~OShO[jO~OWkO~P!QORPOSPOTPOUPOehaWhaYha~OUpOSna[naWna~OShO[sO~OShOWuO~OShOWxO~OUR~",
  goto: "#noPPPPPPPPPPPPPpPP!OPPP!RPPP!]!l!yppp#_iUOQRSW]`bfhnpRaTQi_SritRtlQXOQYQQZRQmbRvnYWOQRbnQbVRncYVOQRbnY[S`fhpQcWRg]Q_SQl`QofQqhRwp",
  nodeNames: "⚠ Comment Program @ , ; Operator ( ) { } [ ] Compound Ident Quoted Args Number String Variable",
  maxTerm: 30,
  skippedNodes: [0,1],
  repeatNodeCount: 1,
  tokenData: "-`~RzX^#upq#uqr$jrs%tst$jtu$juv'mvw$jwx(Uxy)}yz*Sz{$j{|$j|}*X}!O$j!O!P$j!P!Q$j!Q![*^![!]$j!]!^*w!^!_$j!_!`$j!`!a$j!b!c*|!c!},W!}#O,i#O#P$j#P#Q,n#Q#R$j#R#S,W#T#o,s#o#p-U#p#q$j#q#r-Z#y#z#u$f$g#u#BY#BZ#u$IS$I_#u$I|$JO#u$JT$JU#u$KV$KW#u&FU&FV#u~#zYg~X^#upq#u#y#z#u$f$g#u#BY#BZ#u$IS$I_#u$I|$JO#u$JT$JU#u$KV$KW#u&FU&FV#u~$oaU~qr$jst$jtu$jvw$jz{$j{|$j}!O$j!O!P$j!P!Q$j![!]$j!^!_$j!_!`$j!`!a$j!b!c$j#O#P$j#Q#R$j#p#q$j~%wVOr%trs&^s#O%t#O#P&c#P;'S%t;'S;=`'g<%lO%t~&cOb~~&fVOr%trs&{s#O%t#O#P&c#P;'S%t;'S;=`'g<%lO%t~'QVb~Or%trs&^s#O%t#O#P&c#P;'S%t;'S;=`'g<%lO%t~'jP;=`<%l%t~'rSP~OY'mZ;'S'm;'S;=`(O<%lO'm~(RP;=`<%l'm~(XVOw(Uwx(nx#O(U#O#P(s#P;'S(U;'S;=`)w<%lO(U~(sO_~~(vVOw(Uwx)]x#O(U#O#P(s#P;'S(U;'S;=`)w<%lO(U~)bV_~Ow(Uwx(nx#O(U#O#P(s#P;'S(U;'S;=`)w<%lO(U~)zP;=`<%l(U~*SOV~~*XOW~~*^OS~~*cQa~!O!P*i!Q![*^~*lP!Q![*o~*tPa~!Q![*o~*|OT~~+RaR~qr$jst$jtu$jvw$jz{$j{|$j}!O$j!O!P$j!P!Q$j![!]$j!^!_$j!_!`$j!`!a$j!b!c$j#O#P$j#Q#R$j#p#q$j~,]Sc~!Q![,W!c!},W#R#S,W#T#o,W~,nOZ~~,sO[~~,xS^~!Q![,s!c!},s#R#S,s#T#o,s~-ZOX~~-`OY~",
  tokenizers: [0],
  topRules: {"Program":[0,2]},
  tokenPrec: 236
})
