// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
export const parser = LRParser.deserialize({
  version: 14,
  states: "%|OYQPOOOOQO'#Cx'#CxOYQPO'#CcOYQPO'#CfO!oQPO'#CiO!vQPO'#CyOOQO'#Cy'#CyO#eQPO'#CwOfQPO'#CwQOQPOOO#|QPO,58}O$RQPO,59QO$WQPO'#CzOfQPO'#CzO$fQPO'#CkOOQO,59T,59TO$qQPO,59TO$vQPO,59XOYQPO,59cO$}QPO,59cOOQO1G.i1G.iOOQO1G.l1G.lO!QQPO,59fO%fQPO,59fO!QQPO'#CsO%tQPO,59VOOQO1G.o1G.oOOQO1G.s1G.sO&PQPO1G.sOOQO1G.}1G.}OYQPO1G.}OOQO1G/Q1G/QO!QQPO1G/QOOQO,59_,59_OOQO-E6q-E6qOOQO7+$_7+$_OOQO7+$i7+$iOOQO7+$l7+$l",
  stateData: "&X~OjOSPOS~ORPOSPOTPOUPOWQOZRO^SObTOcTOdUOeUOfUO~OU]OWQOZRO^SObTOcTOdUOeUOfUO~O`_O~P!QOWaORmXSmXTmXUmXhmXXmX[mX`mX~ORPOSPOTPOUPOhkXXkX[kX~OXdO~O[eO~OUfOSnX`nXXnX~OShO`_XX_X~O`jO~OXkO~P!QORPOSPOTPOUPOhkaXka[ka~OUpOSna`naXna~OShO`_aX_a~OXsO~OUR~",
  goto: "#koPPPPPPPpPPpPPpP!OPpPPPPP!UPPP![!k!x#^iUOQRSW]abfhnpQ`SRlaQi^RriQXOQYQQZRQmbRtnYWOQRbnQbVRncYVOQRbnY[SafhpQcWRg]S^SaQofQqhRup",
  nodeNames: "⚠ Comment Program @ , ; Operator Parens ( ) Curly { } List [ Args ] Compound Ident Quoted Number String Variable",
  maxTerm: 30,
  skippedNodes: [0,1],
  repeatNodeCount: 1,
  tokenData: "-`~RzX^#upq#uqr$jrs%tst$jtu$juv'mvw$jwx(Uxy)}yz*Sz{$j{|$j|}*X}!O$j!O!P$j!P!Q$j!Q![*^![!]$j!]!^*w!^!_$j!_!`$j!`!a$j!b!c*|!c!},W!}#O,i#O#P$j#P#Q,n#Q#R$j#R#S,W#T#o,s#o#p-U#p#q$j#q#r-Z#y#z#u$f$g#u#BY#BZ#u$IS$I_#u$I|$JO#u$JT$JU#u$KV$KW#u&FU&FV#u~#zYj~X^#upq#u#y#z#u$f$g#u#BY#BZ#u$IS$I_#u$I|$JO#u$JT$JU#u$KV$KW#u&FU&FV#u~$oaU~qr$jst$jtu$jvw$jz{$j{|$j}!O$j!O!P$j!P!Q$j![!]$j!^!_$j!_!`$j!`!a$j!b!c$j#O#P$j#Q#R$j#p#q$j~%wVOr%trs&^s#O%t#O#P&c#P;'S%t;'S;=`'g<%lO%t~&cOe~~&fVOr%trs&{s#O%t#O#P&c#P;'S%t;'S;=`'g<%lO%t~'QVe~Or%trs&^s#O%t#O#P&c#P;'S%t;'S;=`'g<%lO%t~'jP;=`<%l%t~'rSP~OY'mZ;'S'm;'S;=`(O<%lO'm~(RP;=`<%l'm~(XVOw(Uwx(nx#O(U#O#P(s#P;'S(U;'S;=`)w<%lO(U~(sOc~~(vVOw(Uwx)]x#O(U#O#P(s#P;'S(U;'S;=`)w<%lO(U~)bVc~Ow(Uwx(nx#O(U#O#P(s#P;'S(U;'S;=`)w<%lO(U~)zP;=`<%l(U~*SOW~~*XOX~~*^OS~~*cQd~!O!P*i!Q![*^~*lP!Q![*o~*tPd~!Q![*o~*|OT~~+RaR~qr$jst$jtu$jvw$jz{$j{|$j}!O$j!O!P$j!P!Q$j![!]$j!^!_$j!_!`$j!`!a$j!b!c$j#O#P$j#Q#R$j#p#q$j~,]Sf~!Q![,W!c!},W#R#S,W#T#o,W~,nO^~~,sO`~~,xSb~!Q![,s!c!},s#R#S,s#T#o,s~-ZOZ~~-`O[~",
  tokenizers: [0],
  topRules: {"Program":[0,2]},
  tokenPrec: 236
})
