name: CI

on:
  push:
    branches:
      - main
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build-deps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/cache@v5
        with:
          path: deps
          key: deps-${{ runner.os }}-${{ hashFiles('build-deps.sh') }}
      - name: Build dependencies
        run: |
          chmod +x build-deps.sh
          sudo CI=1 ./build-deps.sh
          sudo chmod -R +r deps
      - uses: actions/upload-artifact@v7
        with:
          name: deps-${{ runner.os }}-${{ hashFiles('build-deps.sh') }}
          path: deps

  rust-format-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt
      - run: cargo +nightly fmt --check

  rust-clippy:
    needs: build-deps
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Install system dependencies
        run: |
          chmod +x install-deps-ci.sh
          sudo ./install-deps-ci.sh
      - &fetch-built-deps
        name: Fetch built dependencies
        uses: actions/download-artifact@v8
        with:
          name: deps-${{ runner.os }}-${{ hashFiles('build-deps.sh') }}
          path: deps
      - name: Run clippy
        run: |
          sudo chmod +x deps/swipl/build/src/swipl
          cargo clippy

  rust-test:
    needs: build-deps
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Install system dependencies
        run: |
          chmod +x install-deps-ci.sh
          sudo ./install-deps-ci.sh
      - *fetch-built-deps
      - name: Run tests
        run: |
          sudo chmod +x deps/swipl/build/src/swipl
          cargo test

  js-format-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: pnpm/action-setup@v6
        with:
          version: 10
          cache: true
          run_install: true
      - run: pnpm format-check
