name: Release

on:
  push:
    # tags:
    #   - 'v*'

jobs:
  build:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Linux x86-64
            platform: 'ubuntu-latest'
            scripts: true
            args: ''
          - name: MacOS x86-64
            platform: 'macos-latest'
            scripts: true
            args: '--target x86_64-apple-darwin'
          - name: MacOS aarch64
            platform: 'macos-latest'
            scripts: true
            args: '--target aarch64-apple-darwin'
          - name: Windows x86-64
            platform: 'windows-latest'
            scripts: false
            args: ''

    name: Build - ${{ matrix.name }}
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v6

      - uses: pnpm/action-setup@v6
        with:
          version: 10
          cache: true
          run_install: true

      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.platform == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin' || '' }}

      - name: Install dependencies
        if: matrix.scripts
        run: eval "$(./install-deps.sh)"

      - name: Import shared libraries for bundle
        if: matrix.scripts
        run: ./import-libs.sh

      # TODO: Put this in a script
      - name: Fetch Windows DLL
        if: matrix.platform == 'windows-latest'
        run: |
          Invoke-WebRequest https://www.swi-prolog.org/download/stable/bin/swipl-10.0.2-1.x64.exe -OutFile swipl-installer.exe
          7z x swipl-installer.exe -oswipl-installer
          mkdir libs
          copy swipl-installer\bin\libswipl.dll libs\libswipl-x86_64-windows-msvc.dll

      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SWIPL: ${{ matrix.platform == 'windows-latest' && format('{0}\swipl-installer\bin\swipl.exe', github.workspace) || '' }}
        with:
          tagName: v__VERSION__
          releaseName: v__VERSION__
          releaseDraft: true
          args: ${{ matrix.args }}
