name: Release

on:
  push:
    # tags:
    #   - 'v*'

jobs:
  extract-windows-dll:
    runs-on: windows-latest
    steps:
      - name: Download installer
        run: |
          Invoke-WebRequest https://www.swi-prolog.org/download/stable/bin/swipl-10.0.2-1.x64.exe -OutFile swipl-installer.exe
          7z x swipl-installer.exe -oswipl-installer
      - uses: actions/upload-artifact@v7
        with:
          path: swipl-installer/bin/libswipl.dll
